# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service_a/game_movement.proto for package 'gamemovement'

require 'grpc'
require 'service_a/game_movement_pb'

module Gamemovement
  module GameMoveService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gamemovement.GameMoveService'

      rpc :ValidateMove, ::Gamemovement::ValidateMoveRequest, ::Gamemovement::ValidateMoveResponse
      rpc :ExecuteMove, ::Gamemovement::ExecuteMoveRequest, ::Gamemovement::ExecuteMoveResponse
      rpc :GetValidMoves, ::Gamemovement::GetValidMovesRequest, ::Gamemovement::GetValidMovesResponse
    end

    Stub = Service.rpc_stub_class
  end
end
