// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: game_movement.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type GameStatus int32

const (
	GameStatus_WAITING_FOR_PLAYERS GameStatus = 0
	GameStatus_IN_PROGRESS         GameStatus = 1
	GameStatus_FINISHED            GameStatus = 2
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "WAITING_FOR_PLAYERS",
		1: "IN_PROGRESS",
		2: "FINISHED",
	}
	GameStatus_value = map[string]int32{
		"WAITING_FOR_PLAYERS": 0,
		"IN_PROGRESS":         1,
		"FINISHED":            2,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_game_movement_proto_enumTypes[0].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_game_movement_proto_enumTypes[0]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{0}
}

type CellState int32

const (
	CellState_NEUTRAL CellState = 0
	CellState_OWNED   CellState = 1
)

// Enum value maps for CellState.
var (
	CellState_name = map[int32]string{
		0: "NEUTRAL",
		1: "OWNED",
	}
	CellState_value = map[string]int32{
		"NEUTRAL": 0,
		"OWNED":   1,
	}
)

func (x CellState) Enum() *CellState {
	p := new(CellState)
	*p = x
	return p
}

func (x CellState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellState) Descriptor() protoreflect.EnumDescriptor {
	return file_game_movement_proto_enumTypes[1].Descriptor()
}

func (CellState) Type() protoreflect.EnumType {
	return &file_game_movement_proto_enumTypes[1]
}

func (x CellState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellState.Descriptor instead.
func (CellState) EnumDescriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{1}
}

type Direction int32

const (
	Direction_UP    Direction = 0
	Direction_DOWN  Direction = 1
	Direction_LEFT  Direction = 2
	Direction_RIGHT Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "LEFT",
		3: "RIGHT",
	}
	Direction_value = map[string]int32{
		"UP":    0,
		"DOWN":  1,
		"LEFT":  2,
		"RIGHT": 3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_game_movement_proto_enumTypes[2].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_game_movement_proto_enumTypes[2]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{2}
}

// Mensagens
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_game_movement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Player) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Player) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         CellState              `protobuf:"varint,1,opt,name=state,proto3,enum=gamemovement.CellState" json:"state,omitempty"`
	OwnerId       int32                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_game_movement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetState() CellState {
	if x != nil {
		return x.State
	}
	return CellState_NEUTRAL
}

func (x *Cell) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type GridRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*Cell                `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridRow) Reset() {
	*x = GridRow{}
	mi := &file_game_movement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridRow) ProtoMessage() {}

func (x *GridRow) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridRow.ProtoReflect.Descriptor instead.
func (*GridRow) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{2}
}

func (x *GridRow) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Grid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*GridRow             `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid) Reset() {
	*x = Grid{}
	mi := &file_game_movement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid) ProtoMessage() {}

func (x *Grid) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid.ProtoReflect.Descriptor instead.
func (*Grid) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{3}
}

func (x *Grid) GetRows() []*GridRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GameStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=gamemovement.GameStatus" json:"status,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Grid          *Grid                  `protobuf:"bytes,4,opt,name=grid,proto3" json:"grid,omitempty"`
	Players       map[int32]*Player      `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CurrentTurn   int32                  `protobuf:"varint,6,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_game_movement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{4}
}

func (x *GameState) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_WAITING_FOR_PLAYERS
}

func (x *GameState) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GameState) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GameState) GetGrid() *Grid {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *GameState) GetPlayers() map[int32]*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetCurrentTurn() int32 {
	if x != nil {
		return x.CurrentTurn
	}
	return 0
}

type ValidateMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentState  *GameState             `protobuf:"bytes,1,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	PlayerId      int32                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=gamemovement.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMoveRequest) Reset() {
	*x = ValidateMoveRequest{}
	mi := &file_game_movement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMoveRequest) ProtoMessage() {}

func (x *ValidateMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMoveRequest.ProtoReflect.Descriptor instead.
func (*ValidateMoveRequest) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateMoveRequest) GetCurrentState() *GameState {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *ValidateMoveRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ValidateMoveRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_UP
}

type ExecuteMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentState  *GameState             `protobuf:"bytes,1,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	PlayerId      int32                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=gamemovement.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMoveRequest) Reset() {
	*x = ExecuteMoveRequest{}
	mi := &file_game_movement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMoveRequest) ProtoMessage() {}

func (x *ExecuteMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMoveRequest.ProtoReflect.Descriptor instead.
func (*ExecuteMoveRequest) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteMoveRequest) GetCurrentState() *GameState {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *ExecuteMoveRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ExecuteMoveRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_UP
}

type GetValidMovesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentState  *GameState             `protobuf:"bytes,1,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	PlayerId      int32                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValidMovesRequest) Reset() {
	*x = GetValidMovesRequest{}
	mi := &file_game_movement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValidMovesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValidMovesRequest) ProtoMessage() {}

func (x *GetValidMovesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValidMovesRequest.ProtoReflect.Descriptor instead.
func (*GetValidMovesRequest) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{7}
}

func (x *GetValidMovesRequest) GetCurrentState() *GameState {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *GetValidMovesRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ValidateMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMoveResponse) Reset() {
	*x = ValidateMoveResponse{}
	mi := &file_game_movement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMoveResponse) ProtoMessage() {}

func (x *ValidateMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMoveResponse.ProtoReflect.Descriptor instead.
func (*ValidateMoveResponse) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateMoveResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateMoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecuteMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewState      *GameState             `protobuf:"bytes,1,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	GameFinished  bool                   `protobuf:"varint,2,opt,name=game_finished,json=gameFinished,proto3" json:"game_finished,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMoveResponse) Reset() {
	*x = ExecuteMoveResponse{}
	mi := &file_game_movement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMoveResponse) ProtoMessage() {}

func (x *ExecuteMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMoveResponse.ProtoReflect.Descriptor instead.
func (*ExecuteMoveResponse) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteMoveResponse) GetNewState() *GameState {
	if x != nil {
		return x.NewState
	}
	return nil
}

func (x *ExecuteMoveResponse) GetGameFinished() bool {
	if x != nil {
		return x.GameFinished
	}
	return false
}

func (x *ExecuteMoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ValidMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     Direction              `protobuf:"varint,1,opt,name=direction,proto3,enum=gamemovement.Direction" json:"direction,omitempty"`
	DestinationX  int32                  `protobuf:"varint,2,opt,name=destination_x,json=destinationX,proto3" json:"destination_x,omitempty"`
	DestinationY  int32                  `protobuf:"varint,3,opt,name=destination_y,json=destinationY,proto3" json:"destination_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidMove) Reset() {
	*x = ValidMove{}
	mi := &file_game_movement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidMove) ProtoMessage() {}

func (x *ValidMove) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidMove.ProtoReflect.Descriptor instead.
func (*ValidMove) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{10}
}

func (x *ValidMove) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_UP
}

func (x *ValidMove) GetDestinationX() int32 {
	if x != nil {
		return x.DestinationX
	}
	return 0
}

func (x *ValidMove) GetDestinationY() int32 {
	if x != nil {
		return x.DestinationY
	}
	return 0
}

type GetValidMovesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValidMoves    []*ValidMove           `protobuf:"bytes,1,rep,name=valid_moves,json=validMoves,proto3" json:"valid_moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValidMovesResponse) Reset() {
	*x = GetValidMovesResponse{}
	mi := &file_game_movement_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValidMovesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValidMovesResponse) ProtoMessage() {}

func (x *GetValidMovesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_movement_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValidMovesResponse.ProtoReflect.Descriptor instead.
func (*GetValidMovesResponse) Descriptor() ([]byte, []int) {
	return file_game_movement_proto_rawDescGZIP(), []int{11}
}

func (x *GetValidMovesResponse) GetValidMoves() []*ValidMove {
	if x != nil {
		return x.ValidMoves
	}
	return nil
}

var File_game_movement_proto protoreflect.FileDescriptor

const file_game_movement_proto_rawDesc = "" +
	"\n" +
	"\x13game_movement.proto\x12\fgamemovement\"J\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\"P\n" +
	"\x04Cell\x12-\n" +
	"\x05state\x18\x01 \x01(\x0e2\x17.gamemovement.CellStateR\x05state\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x05R\aownerId\"3\n" +
	"\aGridRow\x12(\n" +
	"\x05cells\x18\x01 \x03(\v2\x12.gamemovement.CellR\x05cells\"1\n" +
	"\x04Grid\x12)\n" +
	"\x04rows\x18\x01 \x03(\v2\x15.gamemovement.GridRowR\x04rows\"\xc8\x02\n" +
	"\tGameState\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.gamemovement.GameStatusR\x06status\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12&\n" +
	"\x04grid\x18\x04 \x01(\v2\x12.gamemovement.GridR\x04grid\x12>\n" +
	"\aplayers\x18\x05 \x03(\v2$.gamemovement.GameState.PlayersEntryR\aplayers\x12!\n" +
	"\fcurrent_turn\x18\x06 \x01(\x05R\vcurrentTurn\x1aP\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.gamemovement.PlayerR\x05value:\x028\x01\"\xa7\x01\n" +
	"\x13ValidateMoveRequest\x12<\n" +
	"\rcurrent_state\x18\x01 \x01(\v2\x17.gamemovement.GameStateR\fcurrentState\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x05R\bplayerId\x125\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x17.gamemovement.DirectionR\tdirection\"\xa6\x01\n" +
	"\x12ExecuteMoveRequest\x12<\n" +
	"\rcurrent_state\x18\x01 \x01(\v2\x17.gamemovement.GameStateR\fcurrentState\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x05R\bplayerId\x125\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x17.gamemovement.DirectionR\tdirection\"q\n" +
	"\x14GetValidMovesRequest\x12<\n" +
	"\rcurrent_state\x18\x01 \x01(\v2\x17.gamemovement.GameStateR\fcurrentState\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x05R\bplayerId\"G\n" +
	"\x14ValidateMoveResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x86\x01\n" +
	"\x13ExecuteMoveResponse\x124\n" +
	"\tnew_state\x18\x01 \x01(\v2\x17.gamemovement.GameStateR\bnewState\x12#\n" +
	"\rgame_finished\x18\x02 \x01(\bR\fgameFinished\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8c\x01\n" +
	"\tValidMove\x125\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x17.gamemovement.DirectionR\tdirection\x12#\n" +
	"\rdestination_x\x18\x02 \x01(\x05R\fdestinationX\x12#\n" +
	"\rdestination_y\x18\x03 \x01(\x05R\fdestinationY\"Q\n" +
	"\x15GetValidMovesResponse\x128\n" +
	"\vvalid_moves\x18\x01 \x03(\v2\x17.gamemovement.ValidMoveR\n" +
	"validMoves*D\n" +
	"\n" +
	"GameStatus\x12\x17\n" +
	"\x13WAITING_FOR_PLAYERS\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02*#\n" +
	"\tCellState\x12\v\n" +
	"\aNEUTRAL\x10\x00\x12\t\n" +
	"\x05OWNED\x10\x01*2\n" +
	"\tDirection\x12\x06\n" +
	"\x02UP\x10\x00\x12\b\n" +
	"\x04DOWN\x10\x01\x12\b\n" +
	"\x04LEFT\x10\x02\x12\t\n" +
	"\x05RIGHT\x10\x032\x96\x02\n" +
	"\x0fGameMoveService\x12U\n" +
	"\fValidateMove\x12!.gamemovement.ValidateMoveRequest\x1a\".gamemovement.ValidateMoveResponse\x12R\n" +
	"\vExecuteMove\x12 .gamemovement.ExecuteMoveRequest\x1a!.gamemovement.ExecuteMoveResponse\x12X\n" +
	"\rGetValidMoves\x12\".gamemovement.GetValidMovesRequest\x1a#.gamemovement.GetValidMovesResponseB\tZ\a./protob\x06proto3"

var (
	file_game_movement_proto_rawDescOnce sync.Once
	file_game_movement_proto_rawDescData []byte
)

func file_game_movement_proto_rawDescGZIP() []byte {
	file_game_movement_proto_rawDescOnce.Do(func() {
		file_game_movement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_movement_proto_rawDesc), len(file_game_movement_proto_rawDesc)))
	})
	return file_game_movement_proto_rawDescData
}

var file_game_movement_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_game_movement_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_game_movement_proto_goTypes = []any{
	(GameStatus)(0),               // 0: gamemovement.GameStatus
	(CellState)(0),                // 1: gamemovement.CellState
	(Direction)(0),                // 2: gamemovement.Direction
	(*Player)(nil),                // 3: gamemovement.Player
	(*Cell)(nil),                  // 4: gamemovement.Cell
	(*GridRow)(nil),               // 5: gamemovement.GridRow
	(*Grid)(nil),                  // 6: gamemovement.Grid
	(*GameState)(nil),             // 7: gamemovement.GameState
	(*ValidateMoveRequest)(nil),   // 8: gamemovement.ValidateMoveRequest
	(*ExecuteMoveRequest)(nil),    // 9: gamemovement.ExecuteMoveRequest
	(*GetValidMovesRequest)(nil),  // 10: gamemovement.GetValidMovesRequest
	(*ValidateMoveResponse)(nil),  // 11: gamemovement.ValidateMoveResponse
	(*ExecuteMoveResponse)(nil),   // 12: gamemovement.ExecuteMoveResponse
	(*ValidMove)(nil),             // 13: gamemovement.ValidMove
	(*GetValidMovesResponse)(nil), // 14: gamemovement.GetValidMovesResponse
	nil,                           // 15: gamemovement.GameState.PlayersEntry
}
var file_game_movement_proto_depIdxs = []int32{
	1,  // 0: gamemovement.Cell.state:type_name -> gamemovement.CellState
	4,  // 1: gamemovement.GridRow.cells:type_name -> gamemovement.Cell
	5,  // 2: gamemovement.Grid.rows:type_name -> gamemovement.GridRow
	0,  // 3: gamemovement.GameState.status:type_name -> gamemovement.GameStatus
	6,  // 4: gamemovement.GameState.grid:type_name -> gamemovement.Grid
	15, // 5: gamemovement.GameState.players:type_name -> gamemovement.GameState.PlayersEntry
	7,  // 6: gamemovement.ValidateMoveRequest.current_state:type_name -> gamemovement.GameState
	2,  // 7: gamemovement.ValidateMoveRequest.direction:type_name -> gamemovement.Direction
	7,  // 8: gamemovement.ExecuteMoveRequest.current_state:type_name -> gamemovement.GameState
	2,  // 9: gamemovement.ExecuteMoveRequest.direction:type_name -> gamemovement.Direction
	7,  // 10: gamemovement.GetValidMovesRequest.current_state:type_name -> gamemovement.GameState
	7,  // 11: gamemovement.ExecuteMoveResponse.new_state:type_name -> gamemovement.GameState
	2,  // 12: gamemovement.ValidMove.direction:type_name -> gamemovement.Direction
	13, // 13: gamemovement.GetValidMovesResponse.valid_moves:type_name -> gamemovement.ValidMove
	3,  // 14: gamemovement.GameState.PlayersEntry.value:type_name -> gamemovement.Player
	8,  // 15: gamemovement.GameMoveService.ValidateMove:input_type -> gamemovement.ValidateMoveRequest
	9,  // 16: gamemovement.GameMoveService.ExecuteMove:input_type -> gamemovement.ExecuteMoveRequest
	10, // 17: gamemovement.GameMoveService.GetValidMoves:input_type -> gamemovement.GetValidMovesRequest
	11, // 18: gamemovement.GameMoveService.ValidateMove:output_type -> gamemovement.ValidateMoveResponse
	12, // 19: gamemovement.GameMoveService.ExecuteMove:output_type -> gamemovement.ExecuteMoveResponse
	14, // 20: gamemovement.GameMoveService.GetValidMoves:output_type -> gamemovement.GetValidMovesResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_game_movement_proto_init() }
func file_game_movement_proto_init() {
	if File_game_movement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_movement_proto_rawDesc), len(file_game_movement_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_movement_proto_goTypes,
		DependencyIndexes: file_game_movement_proto_depIdxs,
		EnumInfos:         file_game_movement_proto_enumTypes,
		MessageInfos:      file_game_movement_proto_msgTypes,
	}.Build()
	File_game_movement_proto = out.File
	file_game_movement_proto_goTypes = nil
	file_game_movement_proto_depIdxs = nil
}
