apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a-container
        image: service-a:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051 
---
apiVersion: v1
kind: Service
metadata:
  name: service-a-service
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051