apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b-container
        image: service-b:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-b-service
spec:
  type: ClusterIP
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051