# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_b/game_state.proto

require 'google/protobuf'


descriptor_data = "\n\x1aservice_b/game_state.proto\x12\tgamestate\"9\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\r\n\x05\x63olor\x18\x04 \x01(\t\"=\n\x04\x43\x65ll\x12#\n\x05state\x18\x01 \x01(\x0e\x32\x14.gamestate.CellState\x12\x10\n\x08owner_id\x18\x02 \x01(\x05\"(\n\x04Grid\x12 \n\x04rows\x18\x01 \x03(\x0b\x32\x12.gamestate.GridRow\")\n\x07GridRow\x12\x1e\n\x05\x63\x65lls\x18\x01 \x03(\x0b\x32\x0f.gamestate.Cell\"\xe7\x01\n\tGameState\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.gamestate.GameStatus\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x1d\n\x04grid\x18\x04 \x01(\x0b\x32\x0f.gamestate.Grid\x12\x32\n\x07players\x18\x05 \x03(\x0b\x32!.gamestate.GameState.PlayersEntry\x1a\x41\n\x0cPlayersEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.gamestate.Player:\x02\x38\x01\"\x11\n\x0fJoinGameRequest\"D\n\x10JoinGameResponse\x12!\n\x06player\x18\x01 \x01(\x0b\x32\x11.gamestate.Player\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x15\n\x13GetGameStateRequest\"8\n\x11GameStateResponse\x12#\n\x05state\x18\x01 \x01(\x0b\x32\x14.gamestate.GameState\"=\n\x16UpdateGameStateRequest\x12#\n\x05state\x18\x01 \x01(\x0b\x32\x14.gamestate.GameState\"*\n\x17UpdateGameStateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*D\n\nGameStatus\x12\x17\n\x13WAITING_FOR_PLAYERS\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x02*#\n\tCellState\x12\x0b\n\x07NEUTRAL\x10\x00\x12\t\n\x05OWNED\x10\x01\x32\xff\x01\n\x10GameStateService\x12\x43\n\x08JoinGame\x12\x1a.gamestate.JoinGameRequest\x1a\x1b.gamestate.JoinGameResponse\x12L\n\x0cGetGameState\x12\x1e.gamestate.GetGameStateRequest\x1a\x1c.gamestate.GameStateResponse\x12X\n\x0fUpdateGameState\x12!.gamestate.UpdateGameStateRequest\x1a\".gamestate.UpdateGameStateResponseB\tZ\x07./protob\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Gamestate
  Player = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.Player").msgclass
  Cell = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.Cell").msgclass
  Grid = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.Grid").msgclass
  GridRow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.GridRow").msgclass
  GameState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.GameState").msgclass
  JoinGameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.JoinGameRequest").msgclass
  JoinGameResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.JoinGameResponse").msgclass
  GetGameStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.GetGameStateRequest").msgclass
  GameStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.GameStateResponse").msgclass
  UpdateGameStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.UpdateGameStateRequest").msgclass
  UpdateGameStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.UpdateGameStateResponse").msgclass
  GameStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.GameStatus").enummodule
  CellState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gamestate.CellState").enummodule
end
