# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service_b/game_state.proto for package 'gamestate'

require 'grpc'
require 'service_b/game_state_pb'

module Gamestate
  module GameStateService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gamestate.GameStateService'

      rpc :JoinGame, ::Gamestate::JoinGameRequest, ::Gamestate::JoinGameResponse
      rpc :GetGameState, ::Gamestate::GetGameStateRequest, ::Gamestate::GameStateResponse
      rpc :UpdateGameState, ::Gamestate::UpdateGameStateRequest, ::Gamestate::UpdateGameStateResponse
    end

    Stub = Service.rpc_stub_class
  end
end
