apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-go
  template:
    metadata:
      labels:
        app: gateway-go
    spec:
      containers:
      - name: gateway-go
        image: gateway_go:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_A_URL
          value: "http://service-a:3002"
        - name: SERVICE_B_URL
          value: "http://service-b:3001"
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: gateway-go
spec:
  type: NodePort
  selector:
    app: gateway-go
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000