// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: service_b/game_state.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type GameStatus int32

const (
	GameStatus_WAITING_FOR_PLAYERS GameStatus = 0
	GameStatus_IN_PROGRESS         GameStatus = 1
	GameStatus_FINISHED            GameStatus = 2
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "WAITING_FOR_PLAYERS",
		1: "IN_PROGRESS",
		2: "FINISHED",
	}
	GameStatus_value = map[string]int32{
		"WAITING_FOR_PLAYERS": 0,
		"IN_PROGRESS":         1,
		"FINISHED":            2,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_service_b_game_state_proto_enumTypes[0].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_service_b_game_state_proto_enumTypes[0]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{0}
}

type CellState int32

const (
	CellState_NEUTRAL CellState = 0
	CellState_OWNED   CellState = 1
)

// Enum value maps for CellState.
var (
	CellState_name = map[int32]string{
		0: "NEUTRAL",
		1: "OWNED",
	}
	CellState_value = map[string]int32{
		"NEUTRAL": 0,
		"OWNED":   1,
	}
)

func (x CellState) Enum() *CellState {
	p := new(CellState)
	*p = x
	return p
}

func (x CellState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellState) Descriptor() protoreflect.EnumDescriptor {
	return file_service_b_game_state_proto_enumTypes[1].Descriptor()
}

func (CellState) Type() protoreflect.EnumType {
	return &file_service_b_game_state_proto_enumTypes[1]
}

func (x CellState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellState.Descriptor instead.
func (CellState) EnumDescriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{1}
}

// Mensagens
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_service_b_game_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Player) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Player) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         CellState              `protobuf:"varint,1,opt,name=state,proto3,enum=gamestate.CellState" json:"state,omitempty"`
	OwnerId       int32                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // 0 se neutro
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_service_b_game_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetState() CellState {
	if x != nil {
		return x.State
	}
	return CellState_NEUTRAL
}

func (x *Cell) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type Grid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*GridRow             `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid) Reset() {
	*x = Grid{}
	mi := &file_service_b_game_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid) ProtoMessage() {}

func (x *Grid) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid.ProtoReflect.Descriptor instead.
func (*Grid) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{2}
}

func (x *Grid) GetRows() []*GridRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type GridRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*Cell                `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridRow) Reset() {
	*x = GridRow{}
	mi := &file_service_b_game_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridRow) ProtoMessage() {}

func (x *GridRow) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridRow.ProtoReflect.Descriptor instead.
func (*GridRow) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{3}
}

func (x *GridRow) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GameStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=gamestate.GameStatus" json:"status,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Grid          *Grid                  `protobuf:"bytes,4,opt,name=grid,proto3" json:"grid,omitempty"`
	Players       map[int32]*Player      `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_service_b_game_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{4}
}

func (x *GameState) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_WAITING_FOR_PLAYERS
}

func (x *GameState) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GameState) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GameState) GetGrid() *Grid {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *GameState) GetPlayers() map[int32]*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

// Request/Response messages
type JoinGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	mi := &file_service_b_game_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{5}
}

type JoinGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_service_b_game_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{6}
}

func (x *JoinGameResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *JoinGameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetGameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateRequest) Reset() {
	*x = GetGameStateRequest{}
	mi := &file_service_b_game_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateRequest) ProtoMessage() {}

func (x *GetGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateRequest.ProtoReflect.Descriptor instead.
func (*GetGameStateRequest) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{7}
}

type GameStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *GameState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateResponse) Reset() {
	*x = GameStateResponse{}
	mi := &file_service_b_game_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateResponse) ProtoMessage() {}

func (x *GameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateResponse.ProtoReflect.Descriptor instead.
func (*GameStateResponse) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{8}
}

func (x *GameStateResponse) GetState() *GameState {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateGameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *GameState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameStateRequest) Reset() {
	*x = UpdateGameStateRequest{}
	mi := &file_service_b_game_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameStateRequest) ProtoMessage() {}

func (x *UpdateGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameStateRequest) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateGameStateRequest) GetState() *GameState {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateGameStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameStateResponse) Reset() {
	*x = UpdateGameStateResponse{}
	mi := &file_service_b_game_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameStateResponse) ProtoMessage() {}

func (x *UpdateGameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateGameStateResponse) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateGameStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RestartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartGameRequest) Reset() {
	*x = RestartGameRequest{}
	mi := &file_service_b_game_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartGameRequest) ProtoMessage() {}

func (x *RestartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartGameRequest.ProtoReflect.Descriptor instead.
func (*RestartGameRequest) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{11}
}

type RestartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartGameResponse) Reset() {
	*x = RestartGameResponse{}
	mi := &file_service_b_game_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartGameResponse) ProtoMessage() {}

func (x *RestartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_game_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartGameResponse.ProtoReflect.Descriptor instead.
func (*RestartGameResponse) Descriptor() ([]byte, []int) {
	return file_service_b_game_state_proto_rawDescGZIP(), []int{12}
}

var File_service_b_game_state_proto protoreflect.FileDescriptor

const file_service_b_game_state_proto_rawDesc = "" +
	"\n" +
	"\x1aservice_b/game_state.proto\x12\tgamestate\"J\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\"M\n" +
	"\x04Cell\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.gamestate.CellStateR\x05state\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x05R\aownerId\".\n" +
	"\x04Grid\x12&\n" +
	"\x04rows\x18\x01 \x03(\v2\x12.gamestate.GridRowR\x04rows\"0\n" +
	"\aGridRow\x12%\n" +
	"\x05cells\x18\x01 \x03(\v2\x0f.gamestate.CellR\x05cells\"\x99\x02\n" +
	"\tGameState\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.gamestate.GameStatusR\x06status\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12#\n" +
	"\x04grid\x18\x04 \x01(\v2\x0f.gamestate.GridR\x04grid\x12;\n" +
	"\aplayers\x18\x05 \x03(\v2!.gamestate.GameState.PlayersEntryR\aplayers\x1aM\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.gamestate.PlayerR\x05value:\x028\x01\"\x11\n" +
	"\x0fJoinGameRequest\"S\n" +
	"\x10JoinGameResponse\x12)\n" +
	"\x06player\x18\x01 \x01(\v2\x11.gamestate.PlayerR\x06player\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x15\n" +
	"\x13GetGameStateRequest\"?\n" +
	"\x11GameStateResponse\x12*\n" +
	"\x05state\x18\x01 \x01(\v2\x14.gamestate.GameStateR\x05state\"D\n" +
	"\x16UpdateGameStateRequest\x12*\n" +
	"\x05state\x18\x01 \x01(\v2\x14.gamestate.GameStateR\x05state\"3\n" +
	"\x17UpdateGameStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12RestartGameRequest\"\x15\n" +
	"\x13RestartGameResponse*D\n" +
	"\n" +
	"GameStatus\x12\x17\n" +
	"\x13WAITING_FOR_PLAYERS\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02*#\n" +
	"\tCellState\x12\v\n" +
	"\aNEUTRAL\x10\x00\x12\t\n" +
	"\x05OWNED\x10\x012\xcd\x02\n" +
	"\x10GameStateService\x12C\n" +
	"\bJoinGame\x12\x1a.gamestate.JoinGameRequest\x1a\x1b.gamestate.JoinGameResponse\x12L\n" +
	"\fGetGameState\x12\x1e.gamestate.GetGameStateRequest\x1a\x1c.gamestate.GameStateResponse\x12X\n" +
	"\x0fUpdateGameState\x12!.gamestate.UpdateGameStateRequest\x1a\".gamestate.UpdateGameStateResponse\x12L\n" +
	"\vRestartGame\x12\x1d.gamestate.RestartGameRequest\x1a\x1e.gamestate.RestartGameResponseB\tZ\a./protob\x06proto3"

var (
	file_service_b_game_state_proto_rawDescOnce sync.Once
	file_service_b_game_state_proto_rawDescData []byte
)

func file_service_b_game_state_proto_rawDescGZIP() []byte {
	file_service_b_game_state_proto_rawDescOnce.Do(func() {
		file_service_b_game_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_b_game_state_proto_rawDesc), len(file_service_b_game_state_proto_rawDesc)))
	})
	return file_service_b_game_state_proto_rawDescData
}

var file_service_b_game_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_b_game_state_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_service_b_game_state_proto_goTypes = []any{
	(GameStatus)(0),                 // 0: gamestate.GameStatus
	(CellState)(0),                  // 1: gamestate.CellState
	(*Player)(nil),                  // 2: gamestate.Player
	(*Cell)(nil),                    // 3: gamestate.Cell
	(*Grid)(nil),                    // 4: gamestate.Grid
	(*GridRow)(nil),                 // 5: gamestate.GridRow
	(*GameState)(nil),               // 6: gamestate.GameState
	(*JoinGameRequest)(nil),         // 7: gamestate.JoinGameRequest
	(*JoinGameResponse)(nil),        // 8: gamestate.JoinGameResponse
	(*GetGameStateRequest)(nil),     // 9: gamestate.GetGameStateRequest
	(*GameStateResponse)(nil),       // 10: gamestate.GameStateResponse
	(*UpdateGameStateRequest)(nil),  // 11: gamestate.UpdateGameStateRequest
	(*UpdateGameStateResponse)(nil), // 12: gamestate.UpdateGameStateResponse
	(*RestartGameRequest)(nil),      // 13: gamestate.RestartGameRequest
	(*RestartGameResponse)(nil),     // 14: gamestate.RestartGameResponse
	nil,                             // 15: gamestate.GameState.PlayersEntry
}
var file_service_b_game_state_proto_depIdxs = []int32{
	1,  // 0: gamestate.Cell.state:type_name -> gamestate.CellState
	5,  // 1: gamestate.Grid.rows:type_name -> gamestate.GridRow
	3,  // 2: gamestate.GridRow.cells:type_name -> gamestate.Cell
	0,  // 3: gamestate.GameState.status:type_name -> gamestate.GameStatus
	4,  // 4: gamestate.GameState.grid:type_name -> gamestate.Grid
	15, // 5: gamestate.GameState.players:type_name -> gamestate.GameState.PlayersEntry
	2,  // 6: gamestate.JoinGameResponse.player:type_name -> gamestate.Player
	6,  // 7: gamestate.GameStateResponse.state:type_name -> gamestate.GameState
	6,  // 8: gamestate.UpdateGameStateRequest.state:type_name -> gamestate.GameState
	2,  // 9: gamestate.GameState.PlayersEntry.value:type_name -> gamestate.Player
	7,  // 10: gamestate.GameStateService.JoinGame:input_type -> gamestate.JoinGameRequest
	9,  // 11: gamestate.GameStateService.GetGameState:input_type -> gamestate.GetGameStateRequest
	11, // 12: gamestate.GameStateService.UpdateGameState:input_type -> gamestate.UpdateGameStateRequest
	13, // 13: gamestate.GameStateService.RestartGame:input_type -> gamestate.RestartGameRequest
	8,  // 14: gamestate.GameStateService.JoinGame:output_type -> gamestate.JoinGameResponse
	10, // 15: gamestate.GameStateService.GetGameState:output_type -> gamestate.GameStateResponse
	12, // 16: gamestate.GameStateService.UpdateGameState:output_type -> gamestate.UpdateGameStateResponse
	14, // 17: gamestate.GameStateService.RestartGame:output_type -> gamestate.RestartGameResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_service_b_game_state_proto_init() }
func file_service_b_game_state_proto_init() {
	if File_service_b_game_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_b_game_state_proto_rawDesc), len(file_service_b_game_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_b_game_state_proto_goTypes,
		DependencyIndexes: file_service_b_game_state_proto_depIdxs,
		EnumInfos:         file_service_b_game_state_proto_enumTypes,
		MessageInfos:      file_service_b_game_state_proto_msgTypes,
	}.Build()
	File_service_b_game_state_proto = out.File
	file_service_b_game_state_proto_goTypes = nil
	file_service_b_game_state_proto_depIdxs = nil
}
